# Generated by Django 3.0.8 on 2020-08-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.IntegerField()),
                ('machine_name', models.CharField(max_length=50)),
                ('selected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.IntegerField(default=0)),
                ('auth_key', models.CharField(max_length=200)),
                ('equipmentExerciseId', models.CharField(max_length=100)),
                ('sett', models.IntegerField(default=0)),
                ('countt', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('startTime', models.CharField(max_length=100)),
                ('endTime', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('auth_key', models.CharField(max_length=200)),
                ('login_date', models.DateTimeField(verbose_name='date published')),
                ('role', models.CharField(max_length=100)),
            ],
        ),
    ]
